project_id = "steunfbcpofecftasvin"

[api]
enabled = true
url = "https://steunfbcpofecftasvin.supabase.co"

[db]
port = 5432

[functions.emails]
verify_jwt = false

[functions.check-snoozed-emails]
verify_jwt = false